import { describe, it, expect } from "vitest";

import { computeDragReorder } from "@/app/playlists/[id]/dragLogic";
import type { PlaylistTrack } from "@/lib/types";

/**
 * These tests target the pure helper extracted from `handleDragEnd` in
 * `app/playlists/[id]/page.tsx`. They are mutation-resistant: swapping
 * `arrayMove(tracks, oldIndex, newIndex)` to
 * `arrayMove(tracks, newIndex, oldIndex)` causes the happy-path and
 * three-element rotation cases below to fail.
 *
 * `rowIds` always mirror the position-aware ids generated by the page
 * component: `${track.id}-pos${i}`. We build them with a small helper to
 * keep the test payloads readable.
 */

function makeTrack(id: string): PlaylistTrack {
  return { id, display_name: id };
}

function rowIdsOf(tracks: PlaylistTrack[]): string[] {
  return tracks.map((t, i) => `${t.id}-pos${i}`);
}

describe("computeDragReorder", () => {
  it("happy path: moving 'A' down by one slot reorders the array correctly", () => {
    const tracks = [makeTrack("A"), makeTrack("B"), makeTrack("C")];
    const rowIds = rowIdsOf(tracks); // ['A-pos0', 'B-pos1', 'C-pos2']

    // Drag A onto B's row → A should land at index 1.
    const result = computeDragReorder("A-pos0", "B-pos1", tracks, rowIds);

    expect(result).not.toBeNull();
    expect(result!.nextTracks.map((t) => t.id)).toEqual(["B", "A", "C"]);
    expect(result!.reorderArgs).toEqual(["B", "A", "C"]);
  });

  it("returns null when active === over (drop on itself)", () => {
    const tracks = [makeTrack("A"), makeTrack("B"), makeTrack("C")];
    const rowIds = rowIdsOf(tracks);

    expect(computeDragReorder("B-pos1", "B-pos1", tracks, rowIds)).toBeNull();
  });

  it("returns null when active id is not in rowIds", () => {
    const tracks = [makeTrack("A"), makeTrack("B"), makeTrack("C")];
    const rowIds = rowIdsOf(tracks);

    expect(
      computeDragReorder("ghost-pos0", "B-pos1", tracks, rowIds),
    ).toBeNull();
  });

  it("returns null when over id is not in rowIds", () => {
    const tracks = [makeTrack("A"), makeTrack("B"), makeTrack("C")];
    const rowIds = rowIdsOf(tracks);

    expect(
      computeDragReorder("A-pos0", "ghost-pos9", tracks, rowIds),
    ).toBeNull();
  });

  it("duplicates: moves the targeted occurrence, not the other twin", () => {
    // Playlist allows the same track id to appear twice — see PlaylistTrack.
    // rowIds disambiguate by position: A-pos0, B-pos1, A-pos2.
    const tracks = [makeTrack("A"), makeTrack("B"), makeTrack("A")];
    const rowIds = rowIdsOf(tracks); // ['A-pos0', 'B-pos1', 'A-pos2']

    // Drag the SECOND 'A' (pos2) onto B's row (pos1) → expected: A, A, B.
    const result = computeDragReorder("A-pos2", "B-pos1", tracks, rowIds);

    expect(result).not.toBeNull();
    expect(result!.reorderArgs).toEqual(["A", "A", "B"]);
    // The first 'A' must be untouched (still the original object reference).
    expect(result!.nextTracks[0]).toBe(tracks[0]);
    // The moved twin is the one that was at index 2.
    expect(result!.nextTracks[1]).toBe(tracks[2]);
    // B (was at index 1) is now at index 2.
    expect(result!.nextTracks[2]).toBe(tracks[1]);
  });

  it("three-element rotation: dragging A onto C produces [B, C, A]", () => {
    // This case is direction-sensitive: arrayMove(t, 0, 2) → [B, C, A],
    // whereas arrayMove(t, 2, 0) → [C, A, B]. Catches arg-swap mutations.
    const tracks = [makeTrack("A"), makeTrack("B"), makeTrack("C")];
    const rowIds = rowIdsOf(tracks);

    const result = computeDragReorder("A-pos0", "C-pos2", tracks, rowIds);

    expect(result).not.toBeNull();
    expect(result!.reorderArgs).toEqual(["B", "C", "A"]);
  });
});
